### ISSUE TITLE
Incomplete analysis of rpython version

### ISSUE THREAD

**Issue by GSam** [pablojorge/brainfuck#10]
It appears that you didn't run rpython --opt=jit which would generate a JIT (or include the annotations). It takes much longer to generate, but it's about 10x faster on mandelbrot from my testing.

**Comment by pablojorge** [comment]
Hi @GSam, I didn't have time until today to explore this. Thanks for the suggestion! I'm really impressed with the results. I added a new version of the interpreter with the required changes, including the optimizations described in https://morepypy.blogspot.com.ar/2011/04/tutorial-part-2-adding-jit.html, and updated the comparison table and the conclusions.

Thanks!

**Comment by GSam** [comment]
I was quite impressed too when I saw the difference too. It's definitely a lot more powerful than I thought and I have a few projects in mind that would find that kind of speed incredibly useful.
