### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by phikal** [pablojorge/brainfuck#2]
I wanted to contribute a few .bf scripts to the repository (and maybe even write a Go interpreter), but then I realized that the repository had no license. 

Is there a specific reason, or just a mistake?

**Comment by pablojorge** [comment]
Hi @phikal ! It was just an oversight, thank you for pointing it out! Now the project has the MIT license.

And thank you for your interest, new scripts and interpreters are more than welcome!
